#!/bin/bash

BASE="/home/husseljo/Arduino/Sketches"
Balance=900
if [ $# -eq 0 ]; then   
	echo "No sketch specified!"
else   
  file_path="$BASE/$1"
  echo "FILE PATH IS: $file_path"
  echo "compiling to arduino"
  arduino-cli compile --fqbn arduino:avr:uno $1
  echo "compiled successfully to Arduino!"
fi

# ard-compile // compile sketch only
# ard-upload // upload sketch only
# ard-serial // open a serial monitor

