#!/bin/bash

BASE="/home/husseljo/Arduino/Sketches"
Balance=900
if [ $# -eq 0 ]; then   
	echo "No sketch specified!"
else   
  file_path="$BASE/$1"
  echo "FILE PATH IS: $file_path"
  echo "opening serial monitor"
  putty /dev/ttyACM0 -serial -sercfg 9600,8,n,1,N
fi
