vim.g.mapleader = " "
require("core.lsp")
require("core.lazy")
-- require("plugins_loader")
-- require("lsp_config")
-- require("lsp-zero-config")
require("config.base")
require("config.mappings")
-- require("terminal")
require("config.run_file_mappings")
require("config.colorscheme")
