#!/usr/bin/bash

last=`tail ~/.config/alacritty/alacritty.yml`
word='opacity'

if [[ "$last" == *"$word"* ]];
then
  # opacity normal
  head -n 45 ~/.config/alacritty/alacritty.yml > ~/.config/alacritty/temp.txt
  mv ~/.config/alacritty/temp.txt ~/.config/alacritty/alacritty.yml
else
  # opacity cool
  echo "window:" >> ~/.config/alacritty/alacritty.yml
  echo " opacity: 0.7" >> ~/.config/alacritty/alacritty.yml
fi
