#!/bin/bash

XMOBAR_CONFIG="$HOME/.xmonad/xmobar.config"

if pgrep -x "xmobar" > /dev/null; then
    echo "xmobar is running. Killing it"
    pkill -x "xmobar"
else
    echo "restarting xmobar."
    xmobar "$XMOBAR_CONFIG" & disown
fi
